### ISSUE TITLE
Download pre-trained models?

### ISSUE THREAD

**Issue by miquelduranfrigola** [recursionpharma/mole_public#2]
Thanks for a very interesting tool.
The "Download pre-trained models" section in the README file remains in TO-DO.
Are you planning to release the pre-trained models soon?
Many thanks!

**Comment by PatWalters** [comment]
+1 on this.  It would be great to perform some comparisons with other methods.

**Comment by sendivogius** [comment]
+1 as well, I also wait for weights publication

**Comment by amirtha-montai** [comment]
+1 on this

**Comment by waqarahmed89** [comment]
+1 on this

**Comment by finlayiainmaclean** [comment]
+1 on this

**Comment by pszmk** [comment]
+1

**Comment by omendezlucio** [comment]
Hi all, 
Thanks for your interest in this project. You can find the model pretrained on GuacaMol and ChEMBL (1.2 million molecules) which is the one used for ablation studies in [reference 48](https://doi.org/10.24433/CO.2928188.v1) of the paper where there is also a jupyter notebook to test the model.
Unfortunately we are not releasing the model pretrained on full ZINC20 for the moment, but possible in the future.

**Comment by victorzhu30** [comment]
Méndez-Lucio, O., Nicolaou, C. & Earnshaw, B. MolE: A Foundation Model for Molecular Graphs Using Disentangled Attention [Source Code]. https://doi.org/10.24433/CO.2928188.v1 (CodeOcean, 2024). 
The link cannot be found
